from functions import *
import time

def PepperVic():
    keyboard.press("d")
    Waitspeed(24)
    keyboard.release("d")
    press(Key.space, 0.1)
    keyboard.press("d")
    time.sleep(0.10)
    keyboard.release("d")
    time.sleep(0.50)
    keyboard.press("w")
    Waitspeed(7)
    keyboard.release("w")
    time.sleep(0.10)
    press(Key.space, 0.1)
    keyboard.press("w")
    time.sleep(0.65)
    Waitspeed(10)
    keyboard.release("w")
    time.sleep(0.10)
    keyboard.press("d")
    Waitspeed(5)
    keyboard.release("d")
    time.sleep(0.10)
    keyboard.press("w")
    press(Key.space, 0.1)
    time.sleep(0.50)
    press(Key.space, 0.1)
    press(Key.space, 0.1)
    keyboard.release("w")
    time.sleep(0.50)
    keyboard.press("w")
    Waitspeed(15)
    keyboard.release("w")
    time.sleep(0.1)
    press(Key.space, 0.1)
    keyboard.press("w")
    time.sleep(0.50)
    keyboard.release("w")
    time.sleep(0.10)
    keyboard.press("w")
    keyboard.press("d")
    Waitspeed(17)
    keyboard.release("w")
    keyboard.release("d")
    time.sleep(0.10)
    press(Key.space, 0.1)
    keyboard.press("d")
    time.sleep(0.50)
    keyboard.release("d")
    time.sleep(0.10)
    keyboard.press("d")
    Waitspeed(18)
    keyboard.release("d")
    time.sleep(0.10)
    keyboard.press("s")
    Waitspeed(3)
    keyboard.release("s")
    ShiftLock()
    keyboard.press("d")
    Waitspeed(1)
    keyboard.release("d")
    keyboard.tap(Key.page_down) 
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down) 
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down) 
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down) 
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    time.sleep(0.15)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")

    
def PepperToCannon():
    press(Key.space, 0.1)
    keyboard.press("d")
    time.sleep(0.50)
    keyboard.release("d")
    time.sleep(0.10)
    keyboard.press("s")
    Waitspeed(15)
    keyboard.release("s")
    time.sleep(0.10)
    keyboard.press("w")
    Waitspeed(5.8)
    keyboard.release("w")
    time.sleep(0.10)
    keyboard.tap(",")
    keyboard.tap(",")
    keyboard.tap(",")
    press(Key.space, 0.1)
    time.sleep(0.1)
    press(Key.space, 0.1)
    time.sleep(2.62)
    keyboard.tap(".")
    time.sleep(0.70)
    press(Key.space, 0.1)
    time.sleep(1.25)

def MountVic():
    keyboard.tap("e")
    time.sleep(2.05)
    press(Key.space, 0.1)
    press(Key.space, 0.1)
    time.sleep(2)
    keyboard.press("w")
    Waitspeed(6.9)
    keyboard.release("w")
    time.sleep(0.10)
    keyboard.press("s")
    Waitspeed(3.5)
    keyboard.release("s")
    keyboard.tap(".")
    keyboard.tap(".")
    keyboard.tap(Key.page_down) 
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down) 
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down) 
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down) 
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    time.sleep(0.15)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")

def CactusVic():
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    press(Key.space, 0.1)
    time.sleep(0.1)
    keyboard.press("d")
    keyboard.press("w")
    Waitspeed(27)
    keyboard.release("w")
    Waitspeed(13)
    keyboard.release("d")
    keyboard.press("w")
    Waitspeed(6.5)
    keyboard.release("w")
    time.sleep(0.05)
    keyboard.press("s")
    Waitspeed(3.6)
    keyboard.release("s")
    keyboard.tap(".")
    press(Key.space, 0.1)
    time.sleep(0.1)
    press(Key.space, 0.1)
    time.sleep(0.5)
    keyboard.tap(".")
    time.sleep(1.85)
    press(Key.space, 0.1)
    time.sleep(1.25)
    keyboard.press("d")
    Waitspeed(6.6)
    keyboard.release("d")
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    keyboard.tap(Key.page_down)
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")

def RoseVic():
    keyboard.press("w")
    keyboard.press("a")
    Waitspeed(15)
    keyboard.release("w")
    Waitspeed(18)
    keyboard.release("a")
    press(Key.space, 0.1)
    time.sleep(0.1)
    keyboard.press("a")
    Waitspeed(4)
    keyboard.press("w")
    Waitspeed(17)
    keyboard.release("a")
    time.sleep(1)
    keyboard.press("w")
    Waitspeed(1.5)
    keyboard.release("w")
    time.sleep(0.10)
    keyboard.press("d")
    Waitspeed(10)
    keyboard.release("d")
    keyboard.tap(",")
    keyboard.tap(",")
    keyboard.press("d")
    Waitspeed(1)
    keyboard.release("d")
    time.sleep(0.50)
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")
    time.sleep(0.15)
    keyboard.tap("o")


def PepperMoveFromDetection():
    press(Key.space, 0.1)
    keyboard.press("d")
    time.sleep(0.50)
    keyboard.release("d")

    keyboard.press("d")
    Waitspeed(3.5)
    keyboard.release("d")

    keyboard.press("s")
    Waitspeed(7)
    keyboard.release("s")

    keyboard.press("w")
    Waitspeed(22)
    keyboard.release("w")

    keyboard.press("d")
    Waitspeed(6.5)
    keyboard.release("d")

    keyboard.press("s")
    Waitspeed(20)
    keyboard.release("s")

    keyboard.press("d")
    Waitspeed(6.5)
    keyboard.release("d")

    keyboard.press("w")
    Waitspeed(29.5)
    keyboard.release("w")

    keyboard.press("d")
    Waitspeed(7.5)
    keyboard.release("d")

    time.sleep(0.10)
    keyboard.press("s")
    Waitspeed(6.5)
    keyboard.press("a")
    Waitspeed(5)
    keyboard.release("s")
    keyboard.release("a")
    

def MountMoveFromDetection():
    press(Key.space, 0.1)
    time.sleep(0.1)
    keyboard.press("d")
    
    keyboard.press("d")
    Waitspeed(5.5)
    keyboard.release("d")

    keyboard.press("w")
    Waitspeed(8)
    keyboard.release("w")

    keyboard.press("d")
    Waitspeed(6.5)
    keyboard.release("d")

    keyboard.press("s")
    Waitspeed(11.5)
    keyboard.release("s")

    keyboard.press("a")
    Waitspeed(6.5)
    keyboard.release("a")

    keyboard.press("s")
    Waitspeed(4.5)
    keyboard.release("s")

    keyboard.press("d")
    Waitspeed(13)
    keyboard.release("d")

    keyboard.press("w")
    Waitspeed(25)
    keyboard.release("w")

    keyboard.press("d")
    Waitspeed(11.5)
    keyboard.release("d")

    keyboard.press("a")
    Waitspeed(6.5)
    keyboard.press("s")
    Waitspeed(6.5)
    keyboard.release("a")
    keyboard.release("s")

def CactusMoveFromDetection():
    keyboard.press("w")
    keyboard.press("a")
    Waitspeed(15)
    keyboard.release("w")
    Waitspeed(20)
    keyboard.release("a")
    press(Key.space, 0.1)
    time.sleep(0.1)
    keyboard.press("w")
    Waitspeed(18)
    keyboard.release("w")

    keyboard.press("d")
    Waitspeed(35.5)
    keyboard.release("d")

    keyboard.press("s")
    Waitspeed(30)
    keyboard.release("s")

    keyboard.press("d")
    Waitspeed(6.5)
    keyboard.release("d")

    keyboard.press("w")
    Waitspeed(26)
    keyboard.release("w")

    keyboard.press("d")
    Waitspeed(4)
    keyboard.release("d")

    keyboard.press("s")
    Waitspeed(40)
    keyboard.release("s")

    keyboard.press("a")
    Waitspeed(6.5)
    keyboard.release("a")

    keyboard.press("w")
    keyboard.press("d")
    Waitspeed(6.5)
    keyboard.release("d")
    keyboard.release("w")


def RoseMoveFromDetection():
    keyboard.press("a")
    Waitspeed(20)
    keyboard.release("a")

    press(Key.space, 0.1)
    time.sleep(0.1)
    keyboard.press("w")
    time.sleep(0.2)
    Waitspeed(10)
    keyboard.release("w")
    time.sleep(0.1)
    
    keyboard.press("d")
    Waitspeed(15)
    keyboard.release("d")

    time.sleep(0.1)
    keyboard.press("a")
    Waitspeed(3.5)
    keyboard.release("a")

    time.sleep(0.1)
    keyboard.press("w")
    Waitspeed(15)
    keyboard.release("w")

    time.sleep(0.1)
    keyboard.press("a")
    Waitspeed(3.5)
    keyboard.release("a")

    keyboard.press("s")
    Waitspeed(15)
    keyboard.release("s")

    time.sleep(0.1)
    keyboard.press("a")
    Waitspeed(3.5)
    keyboard.release("a")

    time.sleep(0.1)
    keyboard.press("w")
    Waitspeed(15)
    keyboard.release("w")

    time.sleep(0.1)
    keyboard.press("a")
    keyboard.press("w")
    Waitspeed(3.5)
    keyboard.release("a")
    keyboard.release("w")

    time.sleep(0.1)
    keyboard.press("d")
    keyboard.press("s")
    Waitspeed(3.5)
    keyboard.release("d")
    keyboard.release("s")
    

def KillVicBees():
    PepperVic()
    if detect_vic_in_screenshot():
        for _ in range(2):
            time.sleep(0.1)
            keyboard.tap(Key.page_up)
        print("Vic detected, killing bees...")
        #kill pattern goes here
        PepperMoveFromDetection()
        return 
    for _ in range(2):
        time.sleep(0.1)
        keyboard.tap(Key.page_up)
    PepperToCannon()
    MountVic()
    if detect_vic_in_screenshot():
        for _ in range(2):
            time.sleep(0.1)
            keyboard.tap(Key.page_up)
        print("Vic detected, killing bees...")
        #kill pattern goes here
        MountMoveFromDetection()
        return 
    CactusVic()
    if detect_vic_in_screenshot():
        for _ in range(2):
            time.sleep(0.1)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
        print("Vic detected, killing bees...")
        #kill pattern goes here
        CactusMoveFromDetection()
        return 
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    keyboard.tap(Key.page_up)
    RoseVic()
    if detect_vic_in_screenshot():
        for _ in range(2):
            time.sleep(0.1)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
            keyboard.tap(Key.page_up)
        print("Vic detected, killing bees...")
        #kill pattern goes here
        RoseMoveFromDetection()
        return 

